# Blender GLTF/GLBエクスポート設定
export_settings:
  # 基本設定 ====================================================================
  # 出力ファイルパス (default: "")
  filepath: ""
  # 既存ファイルの上書き確認 (default: true)
  check_existing: true
  # 出力形式 - Binary(効率的) or JSON(編集しやすい) (default: "")
  export_format: "GLTF_SEPARATE"
  # 著作権情報 (default: "")
  export_copyright: ""
  # エクスポーターの識別子 (default: "")
  gltf_export_id: ""

  # その他の基本設定 ============================================================
  # ソースコレクション (default: "")
  collection: ""
  # コレクションの中心でエクスポート (default: false)
  at_collection_center: false
  # エクスポート設定を保存 (default: false)
  will_save_settings: false
  # フィルターグロブ (default: "*.glb;*.gltf")
  filter_glob: "*.glb;*.gltf"

  # Include設定 ================================================================
  # Limit to
  # 選択オブジェクトのみ (default: false)
  use_selection: false
  # 表示オブジェクトのみ (default: false)
  use_visible: false
  # レンダリング可能なオブジェクトのみ (default: false)
  use_renderable: false
  # アクティブコレクションのみ (default: false)
  use_active_collection: false
  # ネストされたコレクションを含める (default: true)
  use_active_collection_with_nested: true
  # アクティブシーンのみ (default: true)
  use_active_scene: true

  # Data
  # カスタムプロパティをglTF extrasとしてエクスポート (default: false)
  export_extras: false
  # カメラをエクスポート (default: false)
  export_cameras: false
  # ライトをエクスポート (default: false)
  export_lights: false

  # Transform設定 ==============================================================
  # glTF規約のY-up方向でエクスポート (default: true)
  export_yup: true

  # Mesh設定 ==================================================================
  # モディファイアを適用（アーマチュアを除く） (default: false)
  export_apply: false
  # UV座標 (default: true)
  export_texcoords: true
  # 法線 (default: true)
  export_normals: true
  # 接線 (default: false)
  export_tangents: false
  # カスタム属性 (default: false)
  export_attributes: false
  # エッジ (default: false)
  use_mesh_edges: false
  # 頂点 (default: false)
  use_mesh_vertices: false
  # 共有アクセサーを使用 (default: false)
  export_shared_accessors: false

  # 頂点カラー設定 ============================================================
  # 頂点カラーの使用方法 (MATERIAL, ACTIVE, NONE) (default: MATERIAL)
  export_vertex_color: "MATERIAL"
  # すべての頂点カラーをエクスポート (default: false)
  export_all_vertex_colors: false
  # マテリアルがない場合アクティブな頂点カラーを使用 (default: true)
  export_active_vertex_color_when_no_material: true

  # マテリアル設定 ============================================================
  # マテリアル (EXPORT, PLACEHOLDER, NONE) (default: EXPORT)
  export_materials: "EXPORT"
  # 画像フォーマット (AUTO, JPEG, WEBP, NONE) (default: AUTO)
  export_image_format: "AUTO"
  # JPEG品質 (0-100) (default: 75)
  export_jpeg_quality: 75
  # 画像品質 (0-100) (default: 75)
  export_image_quality: 75
  # WebPテクスチャを作成 (default: false)
  export_image_add_webp: false
  # WebPのフォールバックとしてPNGを作成 (default: false)
  export_image_webp_fallback: false
  # オリジナルテクスチャを保持 (default: false)
  export_keep_originals: false

  # Compression(Draco) =======================================================
  # Draco圧縮を使用 (default: false)
  export_draco_mesh_compression_enable: false
  # 圧縮レベル (0-10) (default: 6)
  export_draco_mesh_compression_level: 6
  # 位置の量子化 (0-30) (default: 14)
  export_draco_position_quantization: 14
  # 法線の量子化 (0-30) (default: 10)
  export_draco_normal_quantization: 10
  # UV座標の量子化 (0-30) (default: 12)
  export_draco_texcoord_quantization: 12
  # カラーの量子化 (0-30) (default: 10)
  export_draco_color_quantization: 10
  # その他の量子化 (0-30) (default: 12)
  export_draco_generic_quantization: 12

  # Animation設定 =============================================================
  # アニメーション (default: false)
  export_animations: false
  # アニメーションモード (ACTIONS, ACTIVE_ACTIONS, BROADCAST, NLA_TRACKS, SCENE) (default: ACTIONS)
  export_animation_mode: "ACTIONS"
  # すべてのオブジェクトアニメーションをベイク (default: false)
  export_bake_animation: false
  # 現在のフレームをレスト変換として使用 (default: false)
  export_current_frame: false
  # フレーム範囲を制限 (default: true)
  export_frame_range: true
  # フレームステップ (1-120) (default: 1)
  export_frame_step: 1
  # アニメーションを0から開始 (default: false)
  export_anim_slide_to_zero: false
  # 負のフレーム処理 (SLIDE, CROP) (default: SLIDE)
  export_negative_frame: "SLIDE"
  # すべてのアーマチュアアクションをエクスポート (default: true)
  export_anim_single_armature: true
  # オブジェクトごとにアニメーションを分割 (default: true)
  export_anim_scene_split_object: true
  # アクション間でポーズボーンをリセット (default: false)
  export_reset_pose_bones: false

  # シェイプキー設定 ==========================================================
  # シェイプキー (default: true)
  export_morph: true
  # シェイプキーの法線 (default: true)
  export_morph_normal: true
  # シェイプキーの接線 (default: false)
  export_morph_tangent: false
  # シェイプキーアニメーション (default: true)
  export_morph_animation: true
  # アクション間でシェイプキーをリセット (default: true)
  export_morph_reset_sk_data: true

  # gltf圧縮設定 =============================================================
  # gltfpackを使用してメッシュの簡略化やテクスチャ圧縮を行う (default: false)
  export_use_gltfpack: false
  # KTX2形式でテクスチャを圧縮 (default: true)
  export_gltfpack_tc: true
  # テクスチャエンコード品質 (1-10) (default: 8)
  export_gltfpack_tq: 8
  # メッシュ単純化率 (0-1) (default: 1.0)
  export_gltfpack_si: 1.0
  # 強制的なメッシュ単純化 (default: false)
  export_gltfpack_sa: false
  # 境界頂点をロック (default: false)
  export_gltfpack_slb: false
  # 位置の量子化 (1-16) (default: 14)
  export_gltfpack_vp: 14
  # UV座標の量子化 (1-16) (default: 12)
  export_gltfpack_vt: 12
  # 法線/接線の量子化 (1-16) (default: 8)
  export_gltfpack_vn: 8
  # 頂点カラーの量子化 (1-16) (default: 8)
  export_gltfpack_vc: 8
  # 頂点位置属性タイプ (Integer, Normalized, Floating-point) (default: Integer)
  export_gltfpack_vpi: "Integer"
  # 量子化を無効化 (default: true)
  export_gltfpack_noq: true

# 出力設定
# モデル出力ディレクトリ (default: "./output")
output_directory: "./output"

# FTP設定
ftp_settings:
  # FTPサーバーのホスト名 (default: "")
  host: "ftp-hogehoge.net"
  # FTPポート番号 (default: 21)
  port: 21
  # FTPユーザー名 (default: "")
  username: "*****"
  # FTPパスワード (default: "")
  password: "*****"
  # アップロード先のリモートディレクトリ (default: "/")
  remote_directory: "/assets/model/test/"

# 処理対象ファイルリスト
blend_files:
  - file_path: "./model_01.blend"    # .blendファイルのパス
    output_name: "output_01.gltf"        # 出力ファイル名
    remote_path: "/assets/model/characters/"  # 個別のアップロード先
  - file_path: "./model_02.blend"    # .blendファイルのパス
    output_name: "output_02.gltf"        # 出力ファイル名
    remote_path: "/assets/model/characters/"  # 個別のアップロード先